
###

GET http://localhost/backend/

###

POST https://localhost/backend/
content-type: application/json

{
  "id" : 2,
  "content": "content test"
}

###

POST https://localhost/backend/
content-type: application/json

{
  "id" : 0,
  "content": "content test new"
}

###

GET http://localhost/backend/?delete=3



###

GET https://92c8-94-73-222-14.ngrok-free.app/backend/
